apiVersion: v1
kind: Secret
metadata:
  name: ${app_name}-secret
type: Opaque
data:
  AUTH_CLIENT_SECRET: $AUTH_CLIENT_SECRET_DEV
  AUTH_JWT_SECRET: $AUTH_JWT_SECRET_DEV
  AUTH_STATE: $AUTH_STATE_DEV
  DB_RAD: $DB_MAIN_DEV
  STORAGE_ACCESSKEY: $STORAGE_ACCESSKEY_DEV
  STORAGE_SECRETKEY: $STORAGE_SECRETKEY_DEV