apiVersion: v1
kind: Secret
metadata:
  name: ${app_name}-secret
type: Opaque
data:
  STORAGE_SECRETKEY: $STORAGE_SECRETKEY_DEV
  STORAGE_ACCESSKEY: $STORAGE_ACCESSKEY_DEV
  AUTH_JWT_SECRET: $AUTH_JWT_SECRET_DEV
  AUTH_CLIENT_SECRET: $AUTH_CLIENT_SECRET_DEV
